from lista import *
l = lista()
l.insertNo(9)
l.insertNo(9)
l.insertNo(9)
l.insertNo(9)
l.insertNo(9)
d = lista()
d.insertNo(1)
d.InsertOrdenado(1)
d.InsertOrdenado(1)
d.InsertOrdenado(1)

e = lista()
e = e.intercalados(d,l)
c = l.Push_Repeat_Noord()
#print(type(c), type(l))
print(e.pop(), e.pop(),e.pop(),e.pop(),e.pop(),e.pop(),e.pop(),e.pop(),)
print(d.pop(), d.pop(),d.pop(),d.pop(),d.pop(),d.pop(),d.pop(),d.pop(),)
print(l.pop(), l.pop(),l.pop(),l.pop(),l.pop(),l.pop(),l.pop(),l.pop(),)
